// typehash-strict.test.ts — derives EIP-712 typehashes FROM the actual
// viem type arrays the SDK signs against, then asserts they match the
// hex pinned in the on-chain RezonForge.sol source.
//
// Why this is stricter than typehash.test.ts: that test hashes a
// hand-maintained `TYPEHASH_STRINGS` constant. Drift between the
// constant and the runtime EIP-712 type array (e.g. someone adds a
// field to SPONSOR_INTENT_TYPES but forgets the string) goes
// undetected. This test computes the typehash string from
// SPONSOR_INTENT_TYPES at test time, so any mutation to the live
// type definition — added field, renamed field, reordered field,
// type changed, FeeShare reference removed — flips the keccak hash
// and the test fails loudly with the chain-side hash unchanged.
//
// Lifecycle coverage:
//
//   Solidity typehash literal  →  pinned hex (PINNED below)
//   ──────────────────────────────────────────────────────────
//   Go signer typehash strings →  internal/signer/*.go (peer test
//                                  in the Go suite)
//   TS  typed-data arrays      →  src/intents/*-intent.ts
//                                  (THIS test recomputes from the
//                                   array and asserts == PINNED)
//   UI  typed-data arrays      →  RezonTree-UI/lib/intents/*.ts
//                                  (peer test in UI suite)
//
// Any one of those four layers drifting from the rest will change the
// computed hash. The chain rejects the resulting signature with
// ForgeBadSigner — an opaque revert deep in the broadcast path. This
// test surfaces the drift class instantly, before code reaches a chain.
//
// Update protocol: when a typehash changes, update ALL FOUR layers in
// the same PR. Never one without the others.

import { describe, expect, it } from "vitest";
import { keccak256, stringToBytes } from "viem";

import { COMMIT_INTENT_TYPES } from "./commit-intent";
import { COSPONSOR_INTENT_TYPES } from "./cosponsor-intent";
import { SETTLEMENT_INTENT_TYPES } from "./settlement-intent";
import { SPONSOR_INTENT_TYPES } from "./sponsor-intent";
import { VOTE_INTENT_TYPES } from "./vote-intent";

// Authoritative typehash hexes from contracts/src/RezonForge.sol —
// generated by `keccak256("Type(field1 type1,...)RefStruct(...)")`
// and pinned here to fence the chain side. Update only when the
// contract redeploys with a new typehash, in lockstep with all four
// layers.
const PINNED = {
  // RezonForge.sol:238
  SponsorIntent:
    "0xdd1eeb78695cb1f2fa6ed144a6389e1dc134d00f3a3e6fe895a4a04afea8faf3",
  // RezonForge.sol:246
  CosponsorIntent:
    "0xd9c03036132b2691bcf944f8964155d518856f9766727315bba50e72a9769dd4",
  // RezonForge.sol:250
  CommitIntent:
    "0x6c9a41343766487b62acf6bde0a8c4100342465502c5fe1cf72f3a36114a84a9",
  // RezonForge.sol:254
  VoteIntent:
    "0xce846377b54778704a6c695296cc69e3ebdfc08f87a6ef80f5fa07c7db946e2a",
  // RezonForge.sol:260
  SettlementIntent:
    "0x5fd3f7763a7f80bea9def70b7777f24d1891db2d630a554739eceaef073cd67c",
} as const;

// EIP-712 §"Definition of encodeType":
//   1. Encode primary type as `Name(type1 field1,type2 field2,...)`.
//   2. Append every referenced struct type, sorted alphabetically by
//      name. A reference is any field whose base type (after stripping
//      `[]`) appears as a key in the types map.
//   3. The final string is keccak'd to produce the typehash.
//
// Reproducing this here (rather than calling viem's internal helper)
// is intentional — the test must NOT use the same code path the
// production sign uses, otherwise a bug in the encoder hides the
// drift it's trying to catch.
function encodeType(
  primary: string,
  types: Record<
    string,
    readonly { readonly name: string; readonly type: string }[]
  >,
): string {
  const visit = (name: string): string => {
    const fields = types[name];
    if (!fields) {
      throw new Error(`encodeType: unknown type "${name}"`);
    }
    const args = fields.map((f) => `${f.type} ${f.name}`).join(",");
    return `${name}(${args})`;
  };

  // Walk references transitively, gathering every struct that
  // appears reachable from `primary`. Excludes `primary` itself.
  const referenced = new Set<string>();
  const queue: string[] = [primary];
  while (queue.length > 0) {
    const cur = queue.shift()!;
    const fields = types[cur];
    if (!fields) continue;
    for (const f of fields) {
      const baseType = f.type.replace(/\[\]$/, "");
      if (baseType !== cur && types[baseType] && !referenced.has(baseType)) {
        referenced.add(baseType);
        queue.push(baseType);
      }
    }
  }

  const refsSorted = [...referenced].sort();
  return visit(primary) + refsSorted.map(visit).join("");
}

function typehashOf(
  primary: string,
  types: Record<
    string,
    readonly { readonly name: string; readonly type: string }[]
  >,
): string {
  return keccak256(stringToBytes(encodeType(primary, types)));
}

describe("EIP-712 typehash — derived from runtime type arrays", () => {
  // Each test hashes the LIVE typed-data array the SDK uses to sign.
  // A field rename, type change, or reorder in *-intent.ts flips the
  // hash and the test fails. The test is BEFORE the round-trip path —
  // catches drift at unit-test time, never lets a malformed intent
  // reach a chain.

  it("SponsorIntent", () => {
    const computed = typehashOf("SponsorIntent", SPONSOR_INTENT_TYPES);
    expect(computed).toBe(PINNED.SponsorIntent);
  });

  it("CosponsorIntent", () => {
    const computed = typehashOf("CosponsorIntent", COSPONSOR_INTENT_TYPES);
    expect(computed).toBe(PINNED.CosponsorIntent);
  });

  it("CommitIntent", () => {
    const computed = typehashOf("CommitIntent", COMMIT_INTENT_TYPES);
    expect(computed).toBe(PINNED.CommitIntent);
  });

  it("VoteIntent", () => {
    const computed = typehashOf("VoteIntent", VOTE_INTENT_TYPES);
    expect(computed).toBe(PINNED.VoteIntent);
  });

  it("SettlementIntent", () => {
    const computed = typehashOf("SettlementIntent", SETTLEMENT_INTENT_TYPES);
    expect(computed).toBe(PINNED.SettlementIntent);
  });
});

// Self-test — the encoder is non-trivial enough to deserve its own
// fence. Without this, an encoder bug could silently produce the
// same wrong hash from multiple drifting type arrays.
describe("encodeType — self-test", () => {
  it("primary with no references", () => {
    const types = {
      Foo: [
        { name: "a", type: "uint256" },
        { name: "b", type: "address" },
      ],
    } as const;
    expect(encodeType("Foo", types)).toBe("Foo(uint256 a,address b)");
  });

  it("primary with one referenced struct (alphabetized after primary)", () => {
    const types = {
      Order: [
        { name: "user", type: "address" },
        { name: "item", type: "Item" },
      ],
      Item: [
        { name: "sku", type: "uint256" },
        { name: "qty", type: "uint256" },
      ],
    } as const;
    expect(encodeType("Order", types)).toBe(
      "Order(address user,Item item)Item(uint256 sku,uint256 qty)",
    );
  });

  it("primary with array reference (`[]` stripped before lookup)", () => {
    const types = {
      Cart: [{ name: "items", type: "Item[]" }],
      Item: [{ name: "sku", type: "uint256" }],
    } as const;
    expect(encodeType("Cart", types)).toBe(
      "Cart(Item[] items)Item(uint256 sku)",
    );
  });

  it("references sorted alphabetically (B before C even if listed C-first)", () => {
    const types = {
      A: [
        { name: "c", type: "C" },
        { name: "b", type: "B" },
      ],
      C: [{ name: "x", type: "uint256" }],
      B: [{ name: "y", type: "uint256" }],
    } as const;
    expect(encodeType("A", types)).toBe(
      "A(C c,B b)B(uint256 y)C(uint256 x)",
    );
  });

  it("throws on unknown referenced type", () => {
    const types = { Foo: [{ name: "x", type: "uint256" }] } as const;
    expect(() => encodeType("Bar", types)).toThrow(/unknown type/);
  });
});

// ─────────────────────────────────────────────────────────────────────
// Quadphase v2 envelope + witness typestring fence (PA5 follow-up)
// ─────────────────────────────────────────────────────────────────────
//
// Pinned strings mirror internal/signer/quadphase_envelope.go byte-for-byte
// (Go strings are the source of truth at the Go ↔ Solidity boundary; the
// Solidity side is fenced by typehash_drift_test.go + validator_drift_test.go).
// A drift in any v2 SDK TYPES array — added field, reorder, type rename,
// missing sub-struct ref — flips the encoded type string and the test fails.
// Together with the cross-stack golden vectors in envelope-golden.test.ts,
// this closes the loop: TS arrays produce the same typehash as Go strings,
// which produce the same content/intent hashes Solidity does.

import { ENVELOPE_TYPES } from "./envelope";
import { SPONSOR_WITNESS_TYPES } from "./sponsor-witness";
import { COSPONSOR_WITNESS_TYPES } from "./cosponsor-witness";
import { COMMIT_WITNESS_TYPES } from "./commit-witness";
import { VOTE_WITNESS_TYPES } from "./vote-witness";
import { SETTLE_WITNESS_TYPES } from "./settle-witness";
import { CLAIM_WITNESS_TYPES } from "./claim-witness";
import { REFUND_WITNESS_TYPES } from "./refund-witness";
import { ABANDON_WITNESS_TYPES } from "./abandon-witness";

// Pinned typestrings — every byte matches internal/signer/quadphase_envelope.go.
const PINNED_QPV2_TYPESTRINGS = {
  Envelope:
    "Envelope(address signer,bytes32 qid,uint8 action,uint256 nonce,uint256 expiresAt,bytes32 contentHash,Funds funds)" +
    "FeeShare(address recipient,uint16 basisPoints)" +
    "Funds(address token,uint256 poolIn,uint256 poolOut,uint256 feeAmount,uint16 feeShareBps,FeeShare[] feeShares,uint256 stakeAmount,uint8 stakeOp)",
  SponsorWitness:
    "SponsorWitness(uint8 actionTag,string title,string body,string criteria,string[] tags,address oracle,uint256 sponsorshipFloor,uint256 commitFee,uint256 voteFee,uint256 stakeFloor,uint16 stakeBasisPoints,uint256 fundingDeadline,uint256 noSolutionGracePeriod)",
  CosponsorWitness: "CosponsorWitness(uint8 actionTag,uint256 amount)",
  CommitWitness:
    "CommitWitness(uint8 actionTag,string solutionBody,string[] references)",
  VoteWitness:
    "VoteWitness(uint8 actionTag,Allocation[] allocations,bytes32 salt)" +
    "Allocation(bytes32 solutionId,uint16 basisPoints)",
  SettleWitness:
    "SettleWitness(uint8 actionTag,bytes32 merkleRoot,uint256 totalClaimable,uint256 dustFolded,SlashEntry[] slashes,uint256 leafCount,uint256 slashEntryOffset,uint256 totalSlashEntries)" +
    "SlashEntry(bytes32 intentHash,uint256 amount,uint8 role)",
  ClaimWitness:
    "ClaimWitness(uint8 actionTag,bytes32[] proof,uint256 leafIndex,uint256 leafAmount,uint8 role,uint8 expectedStatus)",
  RefundWitness:
    "RefundWitness(uint8 actionTag,bytes32 sourceIntentHash,uint256 expectedAmount,uint8 expectedStatus)",
  AbandonWitness:
    "AbandonWitness(uint8 actionTag,uint8 expectedStatus,bytes32 reason)",
} as const;

const PINNED_QPV2_TYPEHASHES = {
  Envelope: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.Envelope)),
  SponsorWitness: keccak256(
    stringToBytes(PINNED_QPV2_TYPESTRINGS.SponsorWitness),
  ),
  CosponsorWitness: keccak256(
    stringToBytes(PINNED_QPV2_TYPESTRINGS.CosponsorWitness),
  ),
  CommitWitness: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.CommitWitness)),
  VoteWitness: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.VoteWitness)),
  SettleWitness: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.SettleWitness)),
  ClaimWitness: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.ClaimWitness)),
  RefundWitness: keccak256(stringToBytes(PINNED_QPV2_TYPESTRINGS.RefundWitness)),
  AbandonWitness: keccak256(
    stringToBytes(PINNED_QPV2_TYPESTRINGS.AbandonWitness),
  ),
} as const;

describe("EIP-712 quadphase v2 typestrings — derived from runtime type arrays", () => {
  // Each case computes the encoded type string from the LIVE viem
  // type array using the same encodeType helper validated by the
  // self-test below, then asserts byte-equality against the pinned
  // string. Identical strings ⇒ identical keccak256 ⇒ identical
  // chain-side typehash. Drift surfaces immediately, never reaches
  // the chain.

  it("Envelope (with FeeShare + Funds references)", () => {
    const encoded = encodeType("Envelope", ENVELOPE_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.Envelope);
    expect(typehashOf("Envelope", ENVELOPE_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.Envelope,
    );
  });

  it("SponsorWitness", () => {
    const encoded = encodeType("SponsorWitness", SPONSOR_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.SponsorWitness);
    expect(typehashOf("SponsorWitness", SPONSOR_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.SponsorWitness,
    );
  });

  it("CosponsorWitness", () => {
    const encoded = encodeType("CosponsorWitness", COSPONSOR_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.CosponsorWitness);
    expect(typehashOf("CosponsorWitness", COSPONSOR_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.CosponsorWitness,
    );
  });

  it("CommitWitness", () => {
    const encoded = encodeType("CommitWitness", COMMIT_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.CommitWitness);
    expect(typehashOf("CommitWitness", COMMIT_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.CommitWitness,
    );
  });

  it("VoteWitness (with Allocation reference)", () => {
    const encoded = encodeType("VoteWitness", VOTE_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.VoteWitness);
    expect(typehashOf("VoteWitness", VOTE_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.VoteWitness,
    );
  });

  it("SettleWitness (with SlashEntry reference)", () => {
    const encoded = encodeType("SettleWitness", SETTLE_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.SettleWitness);
    expect(typehashOf("SettleWitness", SETTLE_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.SettleWitness,
    );
  });

  it("ClaimWitness", () => {
    const encoded = encodeType("ClaimWitness", CLAIM_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.ClaimWitness);
    expect(typehashOf("ClaimWitness", CLAIM_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.ClaimWitness,
    );
  });

  it("RefundWitness", () => {
    const encoded = encodeType("RefundWitness", REFUND_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.RefundWitness);
    expect(typehashOf("RefundWitness", REFUND_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.RefundWitness,
    );
  });

  it("AbandonWitness", () => {
    const encoded = encodeType("AbandonWitness", ABANDON_WITNESS_TYPES);
    expect(encoded).toBe(PINNED_QPV2_TYPESTRINGS.AbandonWitness);
    expect(typehashOf("AbandonWitness", ABANDON_WITNESS_TYPES)).toBe(
      PINNED_QPV2_TYPEHASHES.AbandonWitness,
    );
  });
});

// Field-shape contract — pinned arity + ordering for each intent
// type. A drift in the array length or first-field type tells you
// IMMEDIATELY which intent regressed, separately from the typehash
// hex assertion (which only tells you "something changed somewhere").
describe("EIP-712 type arrays — arity + first-field shape", () => {
  type FieldList = readonly { readonly name: string; readonly type: string }[];
  const cases: { name: string; fields: FieldList; arity: number; first: { name: string; type: string } }[] = [
    {
      name: "SponsorIntent",
      fields: SPONSOR_INTENT_TYPES.SponsorIntent,
      arity: 19,
      first: { name: "questionId", type: "bytes32" },
    },
    {
      name: "CosponsorIntent",
      fields: COSPONSOR_INTENT_TYPES.CosponsorIntent,
      arity: 7,
      first: { name: "questionId", type: "bytes32" },
    },
    {
      name: "CommitIntent",
      fields: COMMIT_INTENT_TYPES.CommitIntent,
      arity: 9,
      first: { name: "questionId", type: "bytes32" },
    },
    {
      name: "VoteIntent",
      fields: VOTE_INTENT_TYPES.VoteIntent,
      arity: 9,
      first: { name: "questionId", type: "bytes32" },
    },
    {
      name: "SettlementIntent",
      fields: SETTLEMENT_INTENT_TYPES.SettlementIntent,
      arity: 9,
      first: { name: "questionId", type: "bytes32" },
    },
  ];

  for (const c of cases) {
    it(`${c.name} has exactly ${c.arity} fields, first is {${c.first.name}: ${c.first.type}}`, () => {
      expect(c.fields.length).toBe(c.arity);
      expect(c.fields[0]).toEqual(c.first);
    });
  }
});
